spring.application.name=saitynas_galutinis
spring.datasource.url=jdbc:postgresql://localhost:5432/saitynas_db
spring.datasource.username=saitynas_user
spring.datasource.password=saitynas_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
currency.api.key=cur_live_9dGVlGKGhgvYtbznKKyNkLz1AOTUDnpirttX5r6s